# Generated by Django 5.2.8 on 2025-12-29 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0003_earlyclockoutrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
